# Generated by Django 5.2.1 on 2025-06-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='employee_id',
        ),
    ]
