# Generated by Django 5.2.1 on 2025-06-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0002_remove_employeeprofile_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='manager',
        ),
    ]
