# Generated by Django 5.2.1 on 2025-06-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0005_employeeprofile_first_name_employeeprofile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancerecord',
            name='customer_base_target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='customer_base_volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='date_recorded',
            field=models.DateField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='distribution_target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='distribution_volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='revenue_target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='revenue_volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='sales_target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='sales_volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='team_engagement_score',
            field=models.IntegerField(default=0),
        ),
    ]
