# Generated by Django 5.2.1 on 2025-06-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0006_alter_performancerecord_customer_base_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancerecord',
            name='date_recorded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
