# Generated by Django 5.2.1 on 2025-06-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0007_alter_performancerecord_date_recorded'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='data_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
