# Generated by Django 5.2.1 on 2025-06-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0009_employeeprofile_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancerecord',
            name='date_recorded',
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='performance_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='performance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
