# Generated by Django 5.2.1 on 2025-06-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0011_alter_evaluation_evaluator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('HIGH_MANAGER', 'High Level Manager'), ('MIDDLE_MANAGER', 'Middle Level Manager'), ('MANAGER', 'Low Level Manager'), ('EMPLOYEE', 'Employee')], max_length=20),
        ),
    ]
