# Generated by Django 5.2.1 on 2025-09-14 09:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0014_evaluation_areas_for_improvement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancerecord',
            name='kpi_values',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='customer_base_target',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='customer_base_volume',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='distribution_target',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='distribution_volume',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='revenue_target',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='revenue_volume',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='sales_target',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='sales_volume',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='team_engagement_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HR', 'HR'), ('HIGH_MANAGER', 'High Level Manager'), ('MIDDLE_MANAGER', 'Middle Level Manager'), ('MANAGER', 'Low Level Manager'), ('EMPLOYEE', 'Employee')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('kpi_type', models.CharField(choices=[('QUANTITATIVE', 'Quantitative'), ('QUALITATIVE', 'Qualitative'), ('BOOLEAN', 'Boolean')], default='QUANTITATIVE', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('target_direction', models.CharField(choices=[('HIGHER', 'Higher is Better'), ('LOWER', 'Lower is Better')], default='HIGHER', max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_kpis', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'unique_together': {('role', 'name')},
            },
        ),
    ]
