# Generated by Django 6.0 on 2026-01-02 18:21

import django.core.validators
import django.db.models.deletion
import performance_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0015_performancerecord_kpi_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=performance_app.models.generate_default_email, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('EMPLOYEE', 'Employee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('EMPLOYEE', 'Employee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('period', models.CharField(choices=[('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly')], max_length=10)),
                ('category', models.CharField(choices=[('SALES', 'Sales Achievement'), ('PROJECT', 'Project Completion'), ('CLIENT', 'Client Satisfaction'), ('TEAM', 'Team Collaboration'), ('INNOVATION', 'Innovation'), ('QUALITY', 'Quality Improvement'), ('LEADERSHIP', 'Leadership'), ('TRAINING', 'Training/Development'), ('OTHER', 'Other')], max_length=20)),
                ('date_achieved', models.DateField()),
                ('evidence', models.TextField(blank=True, help_text='Optional evidence or supporting details')),
                ('admin_rating', models.IntegerField(blank=True, help_text='Admin rating from 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('admin_feedback', models.TextField(blank=True, help_text='Admin feedback on this achievement')),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Whether this achievement is visible to others')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_achievements', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='performance_app.employeeprofile')),
                ('rated_by', models.ForeignKey(blank=True, help_text='Admin who rated this achievement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rated_achievements', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-date_achieved', '-data_created'],
            },
        ),
        migrations.CreateModel(
            name='AchievementRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateTimeField(auto_now_add=True)),
                ('quality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('impact', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('effort', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('innovation', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True, help_text='Suggestions for improvement')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='performance_app.achievement')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating_date'],
                'unique_together': {('achievement', 'rated_by')},
            },
        ),
    ]
