# Generated by Django 6.0 on 2026-01-03 22:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0017_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the work log')),
                ('period', models.CharField(choices=[('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly')], default='DAY', max_length=10)),
                ('hours_worked', models.DecimalField(decimal_places=2, help_text='Total hours worked during this period', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('work_description', models.TextField(help_text='Description of work done during this period')),
                ('achievements', models.TextField(blank=True, help_text='Key achievements or tasks completed')),
                ('challenges', models.TextField(blank=True, help_text='Challenges faced or obstacles encountered')),
                ('next_steps', models.TextField(blank=True, help_text='Plans for next period or follow-up actions')),
                ('admin_rating', models.IntegerField(blank=True, help_text='Admin rating from 1-10 based on work done', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('admin_feedback', models.TextField(blank=True, help_text='Admin feedback on the work log')),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False, help_text='Whether the work log has been submitted')),
                ('is_reviewed', models.BooleanField(default=False, help_text='Whether the work log has been reviewed by admin')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_work_logs', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='performance_app.employeeprofile')),
                ('rated_by', models.ForeignKey(blank=True, help_text='Admin who rated this work log', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rated_work_logs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_work_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Log',
                'verbose_name_plural': 'Work Logs',
                'ordering': ['-date', '-data_created'],
                'unique_together': {('employee', 'date', 'period')},
            },
        ),
    ]
